- src/redux/selectors/file_info.js
For https://github.com/lbryio/lbry-app/issues/1285
> fix: check that claim exists before checking value

- README.md
The current documentation was a bit confusing for me as new dev, so I've updated the docs to let other know on how to actually use this repository.
> Update documentation to explain how to build the module

- yarn.lock
Several modules are outdated and potentially vulnerable
> Upgrade module dependencies

- src/constants/modal_types.js
- See issue: https://github.com/lbryio/lbry-app/issues/1442
- Required by: https://github.com/lbryio/lbry-app/pull/1441
> Add modal-type for external links

- dist/bundle.js
- src/redux/actions/search.js
If the autocomplete api returns a string with no spaces, it is a valid lbry uri. We should treat it as such.
> handle lbry uris in autocomplete results

- src/redux/reducers/claims.js
Was fixed before in lbry-app, but lost during redux migration
Allows for selection of updated channels in the publish screen channel dropdown
> include channel updates in claim data

- dist/bundle.js
- src/constants/modal_types.js
- src/redux/reducers/notifications.js
Changes needed for [PR#1525](https://github.com/lbryio/lbry-app/pull/1525) on lbry app.
> Add confirm transaction modal.

- dist/bundle.js
- src/redux/reducers/notifications.js
- src/types/Notification.js
this was getting in the way of other data I needed to pass to a notification and will continue to be an issue for other use cases
> remove notification props

- src/redux/reducers/search.js
> Revert "do not reset search query on HISTORY_NAVIGATE"

- dist/bundle.js
- src/constants/thumbnail_upload_statuses.js
- src/index.js
- src/redux/actions/notifications.js
add constants to this repo
required for [/lbryio/lbry-app/pull/1248](https://github.com/lbryio/lbry-app/pull/1248)
> Thumbnail upload statuses

- src/lbry.js
Required by https://github.com/lbryio/lbry-app/pull/1542
> Add 3D-file support for getMediaType function

- dist/bundle.js
- src/redux/selectors/navigation.js
"Send & Recieve" changed to the correct "Send & Receive".
> Big typo fix

- dist/bundle.js
- src/redux/actions/search.js
@seanyesmunt this should be perfect and not impact anything. It allows us to specify these values in the apps.
> added size and from values for query and as input to dosearch.

- dist/bundle.js
- src/redux/actions/wallet.js
> update tip message

- dist/bundle.js
- src/index.js
- src/redux/selectors/claims.js
- src/util/claim.js
Adds two new selectors to be used in the app. One takes an array of uris, and returns the count of nsfw claims.
The other takes a channel uri and returns the number of nsfw claims on the current page.
> Select nsfw content

- dist/bundle.js
- src/redux/selectors/wallet.js
[/lbryio/lbry-app/issues/608](https://github.com/lbryio/lbry-app/issues/608)
Label `abandon` claims like `update` claims.
I'm not sure if VS Code, es-lint, or what added those parentheses to the fee value expression but I find it more readable.
> label abandon(ed) claims

- dist/bundle.js
- src/redux/reducers/claims.js
[/lbryio/lbry-desktop/issues/1255](https://github.com/lbryio/lbry-desktop/issues/1255)
> save channel claim data to claimsByUri

- dist/bundle.js
- package.json
- webpack.config.js
See https://github.com/lbryio/lbry-desktop/issues/1485
> Add 'yarn dev' for watch mode (dev)

- dist/bundle.js
- src/redux/actions/search.js
- src/redux/selectors/claims.js
- src/redux/selectors/search.js
So it makes the request to the correct endpoint
> trim "/" from search query

- src/constants/modal_types.js
Let me know if any more in the lbry-redux branch is required.
> adds SOCIAL_SHARE

- dist/bundle.js
- src/lbryURI.js
https://github.com/lbryio/lbry-redux/issues/88
> Fix: #88 removes obsolete pending_claim regex match

- .prettierrc.json
- dist/bundle.js
- src/index.js
- src/lbry.js
- src/redux/actions/wallet.js
- src/redux/reducers/claims.js
- src/redux/selectors/claims.js
- src/redux/selectors/wallet.js
- src/util/formatCredits.js
> Support for lbrynet daemon v0.30.0

- dist/bundle.js
- src/redux/actions/claims.js
Weren't checking the right thing with the new daemon
https://github.com/lbryio/lbry-desktop/issues/2073
> fix: check for sucessful abaondon and add toast on success

- dist/bundle.js
- src/redux/reducers/wallet.js
- src/redux/selectors/wallet.js
With the new daemon, pending tx's were being displayed at the bottom of the list.
> Fix: always show correct order for tx list

- README.md
Updated contributing and added an MIT license badge!
> Created a modern readme for redux module!

- dist/bundle.js
- src/redux/selectors/claims.js
https://github.com/lbryio/lbry-desktop/issues/2059
> modifies totalpages selector to take pageSize param

- dist/bundle.js
- src/redux/reducers/claims.js
So we don't re-resolve your own claims if we don't need to.
> add claim to claimsByUri after claim_list_mine

- dist/bundle.js
- src/redux/actions/search.js
- src/util/debounce.js
So we aren't hitting the api for every keystroke
> debounce search suggestion call

- dist/bundle.js
- src/redux/actions/claims.js
For https://github.com/lbryio/lbry-desktop/issues/2172
> support for lazy loading in the desktop app

- dist/bundle.js
- src/lbry.js
- src/redux/actions/claims.js
- webpack.config.js
resolve param changed from uri/uris, to urls.
> maint: support 0.31 SDK

- dist/bundle.js
- src/lbryURI.js
multisig addresses begin with an r - https://explorer.lbry.io/address/rH9eJbSrWoBUtkXA3hvkrysbG8T2CHGKMm
> allow multisig addresses

- dist/bundle.js
- src/index.js
- src/redux/actions/search.js
- src/redux/selectors/claims.js
- src/redux/selectors/search.js
Needed for https://github.com/lbryio/lbry-desktop/pull/2384
@akinwale I did a search on `lbry-android`. I don't see any of the functions I've removed, this shouldn't be a breaking change.
> Remove references to desktop app navigation state

- dist/bundle.es.js
- dist/flow-typed/Claim.js
- flow-typed/Claim.js
- src/index.js
- src/redux/selectors/claims.js
The same as thumbnail selector, but different. Probably going to add more of these for individual channel metadata
> Add cover selector

- dist/bundle.es.js
- dist/flow-typed/Claim.js
- src/redux/selectors/file_info.js
DateTime now uses timestamps rather than block_show
file_info searchdownloads selector no longer errors looking for certificateId.
> Removes block show and fixes download search selector

- dist/bundle.es.js
- dist/flow-typed/Claim.js
- flow-typed/Claim.js
- src/index.js
Also cleaned up some metadata
depth is no longer there, replaced by confirmations
added city
added featured to channel
removed email/homepage
> add: isNSFW + others

- dist/flow-typed/Claim.js
- flow-typed/Claim.js
SDK has updated this amount also.
> fix: change fee amount to string

- src/redux/selectors/search.js
this tries to fix [#2489](https://github.com/lbryio/lbry-desktop/issues/2489) on lbry-desktop
> set correct suggestion type for lbry URIs

- dist/bundle.es.js
- src/constants/search.js
- src/lbryURI.js
- src/redux/actions/claims.js
- src/redux/selectors/claims.js
- src/redux/selectors/search.js
Also changed `doClaimSearch` to move `amount` into the options object. It didn't really make sense to have it separate. It can be changed with `page_size`
> add 'tag' as search suggestion

- dist/bundle.es.js
- src/redux/actions/claims.js
- src/redux/actions/wallet.js
Adds additional logic to tell if something is a support or not. Also, fixes snackbar. Removes uri which is not used.
> feat: supports vs tips

- dist/bundle.es.js
- dist/flow-typed/Publish.js
- flow-typed/Publish.js
- src/index.js
- src/redux/actions/claims.js
- src/redux/actions/publish.js
- src/redux/reducers/publish.js
- src/redux/selectors/publish.js
doPublish selects redux state for publish 
re: comments here https://github.com/lbryio/lbry-redux/pull/158
@akinwale How bad are the compatibility issues?
> MERGE AFTER 34 RELEASE - enables publish for desktop - flow skipped WIP

- dist/bundle.es.js
- dist/flow-typed/Blocklist.js
- flow-typed/Blocklist.js
- src/constants/action_types.js
- src/index.js
- src/redux/actions/blocked.js
- src/redux/reducers/blocked.js
- src/redux/selectors/blocked.js
- src/redux/selectors/file_info.js
provides user capability to block channels
> Channel filter mm

- dist/bundle.es.js
- src/redux/actions/publish.js
Fixes https://github.com/lbryio/lbry-desktop/issues/2709 and tags not repopulating on edit
> Fix: publish bugs while editing

- dist/bundle.es.js
- dist/flow-typed/Lbry.js
- flow-typed/Lbry.js
- src/lbry.js
- src/redux/actions/wallet.js
Support for the available balance. Doesn't include any of the new fields.
Enabled @flow support on wallet file, didn't fix other issues.
> feat: 0.39 account balance basic API support

- dist/bundle.es.js
- src/index.js
- src/lbry.js
- src/lbryURI.js
- src/redux/actions/publish.js
- src/redux/actions/wallet.js
- src/redux/reducers/claims.js
- src/redux/selectors/claims.js
- src/redux/selectors/publish.js
Random fixes for canonical_url
> canonical_url fixes

- dist/bundle.es.js
- src/constants/transaction_list.js
- src/index.js
- src/redux/selectors/wallet.js
does transaction filtering and pagination in selectors
> transaction pagination selectors

- dist/bundle.es.js
- src/index.js
- src/redux/selectors/claims.js
- src/redux/selectors/file_info.js
Responds to comments on 
https://github.com/lbryio/lbry-redux/pull/201
> Pagination rebase

- dist/bundle.es.js
- src/redux/actions/claims.js
- src/redux/actions/publish.js
- src/redux/actions/wallet.js
- src/redux/selectors/claims.js
Fixes issue updating claims with no thumbnail url
Also grabs locations/languages if they were set in the claim (mostly from youtube channels)
grabs locations from claim on edits (mostly from youtube channels)
> feat: add blocking + fixes

- dist/bundle.es.js
- dist/flow-typed/i18n.js
- flow-typed/i18n.js
- src/redux/actions/wallet.js
- src/redux/reducers/claims.js
- src/redux/selectors/wallet.js
- src/util/format-credits.js
Also looks like some additional bundle stuff that wasn't updated in previous PR's
I also added a fix for pending channels
> add commas to formatCredits

- dist/bundle.es.js
- src/redux/actions/claims.js
https://github.com/lbryio/lbry-desktop/pull/3026
> returns channel create result for use outside lbry-redux

- dist/bundle.es.js
- src/redux/actions/claims.js
- src/redux/reducers/claims.js
Replaces https://github.com/lbryio/lbry-redux/pull/223
> update myclaims on Abandon Succeeded

- dist/bundle.es.js
- dist/flow-typed/Lbry.js
- flow-typed/Lbry.js
- src/constants/headers.js
- src/constants/speech_urls.js
- src/index.js
- src/lbry.js
- src/redux/actions/publish.js
Changes sdk api call if method=publish and daemonConnectionString contains "proxy" (interested in better way to do this).
> Tv publish api

- dist/bundle.es.js
- src/index.js
- src/lbry.js
Wasn't able to test immediately due to signin screen. If this isn't the best, I can duplicate the code on desktop side.
> exposes api call for use by tv update

- dist/bundle.es.js
- dist/flow-typed/File.js
- dist/flow-typed/Lbry.js
- dist/flow-typed/Transaction.js
- flow-typed/File.js
- flow-typed/Lbry.js
- flow-typed/Transaction.js
- src/lbry.js
- src/redux/actions/claims.js
- src/redux/actions/comments.js
- src/redux/actions/file_info.js
- src/redux/actions/wallet.js
- src/redux/reducers/comments.js
- src/redux/selectors/file_info.js
> maint: support 0.44 SDK

- dist/bundle.es.js
- src/redux/reducers/claims.js
So we don't need to re-resolve to get channel counts
> add channel item count for canonical url as well as vanity url

- dist/bundle.es.js
- src/redux/reducers/claims.js
> same fix for streams

- dist/bundle.es.js
- src/redux/selectors/tags.js
This should eventually remove bad tags too since we use this selector when building lists of tags.
Merging because the app is crashing without this
> make sure we never store tags as something other than a string

- dist/bundle.es.js
- src/redux/actions/sync.js
- src/redux/reducers/blocked.js
sync for blocked channels was looking for 'blockedChannels' in preference store rather than 'blocked'.
> fixes blockedChannel sync

- dist/bundle.es.js
- src/redux/actions/comments.js
- src/redux/reducers/comments.js
Previous error messages in comment actions were misleading; these are concise and descriptive
> Corrects error messages

- src/lbry.js
Must have done this locally and forgot about it
Required for lbryio/lbry-desktop#3511
> Add html to the list of "documents"

- dist/bundle.es.js
- src/util/format-credits.js
Step towards resolving lbryio/lbry-desktop#4140
> add case for when amount is undefined in formatCredits instead of returning 0

- dist/bundle.es.js
- dist/flow-typed/Claim.js
- flow-typed/Claim.js
- src/index.js
- src/redux/actions/claims.js
- src/redux/actions/publish.js
- src/redux/reducers/claims.js
- src/redux/selectors/claims.js
- src/util/merge-claim.js
> Revert "support pending channels"

- src/redux/actions/wallet.js
[lbry-desktop] [4429](https://github.com/lbryio/lbry-desktop/issues/4429): `Unresolved string: "You sent ${amount} LBC"`
Corrected error in commit c9492522.
> Fix unresolved "You sent ${amount} LBC"

- src/redux/actions/claims.js
- src/redux/actions/file.js
- src/redux/actions/notifications.js
- src/redux/reducers/publish.js
> Revert "Some new translation strings"

- dist/bundle.es.js
- src/constants/settings.js
Setting for users to specify always search in a language
> add searchInLangage setting

- dist/bundle.es.js
- src/redux/reducers/publish.js
- src/redux/selectors/publish.js
also fix publish language default
> persist publish language

- dist/bundle.es.js
- src/index.js
- src/redux/actions/wallet.js
- src/redux/reducers/wallet.js
- src/redux/selectors/wallet.js
Needed a way to tell which buttons to show or disable during pending state.
> better track txids for large wallet operations

- dist/flow-typed/Lbry.js
- flow-typed/Lbry.js
see: https://github.com/lbryio/lbry-sdk/pull/3201
> connection_status is dead, long live connected

- dist/bundle.es.js
- src/redux/actions/claims.js
For lbry-desktop's `Publish page + reposts 4563`
> doFetchClaimListMine: add 4th param to filter out `claim_type`

- dist/flow-typed/Lbry.js
- flow-typed/Lbry.js
Reverts lbryio/lbry-redux#393
revert the revert!
> Revert "Revert "connection_status is dead, long live connected""

- dist/bundle.es.js
- src/redux/selectors/claims.js
> Revert "fix claimHasSource selector"

- dist/flow-typed/CoinSwap.js
- flow-typed/CoinSwap.js
Some updates, hopefully final.
> CoinSwap: handle "receiving/received LBC"

- dist/bundle.es.js
- src/redux/middleware/shared-state.js
If sync is triggered by an ACTION, delay it in case another action is about to happen (eg, follow).
> delay preference set two seconds

- dist/bundle.es.js
- src/redux/actions/publish.js
The previous PR only covered the scenario of changing between NEW and EDIT. This one covers "uploading new".
> Clear 'thumbnailError' when uploading new one

- dist/bundle.es.js
- src/redux/selectors/publish.js
https://github.com/lbryio/lbry-desktop/issues/6132#issuecomment-860168781
Thanks @infinite-persistence for noticing, should be fixed now
> Fix breaking when no languages set

- dist/bundle.es.js
- src/index.js
- src/redux/selectors/collections.js
[Required Changes for https://github.com/lbryio/lbry-desktop/pull/6921]
> Playback and List control changes

- dist/bundle.es.js
- src/redux/actions/publish.js
added a cb function to doUploadThumbnail so that the list form can be filled with the thumbnail upload response
> Changes for list thumbnail upload
