lbryio/lbry-redux

src/lbry.js

Rebased from LBRY/lbry-app PR# 1304 with corrections requested by Codacy (Though may still complain regarding spacing).
This just makes the code for finding documents a lot easier. the regex patterns and the media type are converted into keypairs, [regex, mediatype] which is then reduced to a single value, which will either be the original filename if there are no matching extensions, or the mediatype. So long as the mediatype does not contain an extension at the end of the string, this system should work far more simply.
This will also allow for easier addition of new extensions to the function, so long as they all follow the same pattern for the regex:
^ = Start of string
.+ = 1 or more characters of any type
. = A literal dot
(a|b|c) = A list of ORed extensions within a capture group …

Simplify Media Identification Function

---

src/redux/actions/wallet.js

While investigating the 0LBC doSendSupport issue (lbry-app #738) I noticed that if I sent a tip, I had to restart the app to send another, because this wasn't being dispatched.

mark support transaction as completed

---

src/redux/actions/wallet.js

I copied the pattern from support payment completion. It displays the error in the snackbar and resets `state.wallet.sendingSupport` to false so when a user clicks "send a tip" again, the Send button in the modal is enabled.
Disabling of the Send button until the amount is positive coming soon in the app repo...

handle doSendSupport error like complete

---

dist/bundle.js
src/redux/selectors/navigation.js

Changed the links to move settings to the top level, and moved "transactions" to have higher priority. Also moved "backup" inside wallet.

Update nav links

---

dist/bundle.js
src/redux/actions/search.js

If the search suggestion api returns a query that is the same as the one the user typed in the search bar, we should remove it so there aren't two identical search suggestions.
Fixes https://github.com/lbryio/lbry-app/issues/1495

filter search suggestions so the search query isn't suggested twice

---

src/redux/reducers/search.js

This was breaking the back button fix I'm working on for [lbry-app/issues/1457](https://github.com/lbryio/lbry-app/issues/1457)

do not reset search query on HISTORY_NAVIGATE

---

src/index.js
src/lbryURI.js

This function will parse a lbry URI and convert it to an https protocol, Let me know if this is the correct place to add it, we may need to use it on lbry-android sometime(tap on a video to share an url or something like that)
This PR is needed for [PR on lbry-app#1486](https://github.com/lbryio/lbry-app/pull/1486)
So for example given this URI:
`lbry://why-doesn-t-capitalism-work-for#36cd5b217bcc4083a6fc35cc4de2cc1196581ef9`
changes to:
`https://open.lbry.io/why-doesn-t-capitalism-work-for#36cd5b217bcc4083a6fc35cc4de2cc1196581ef9`

Add function to convert an URI to  an url that can be shared and opened with lbry-app

---

dist/bundle.js
src/lbryURI.js

Pass correct values to builduri. Otherwise, you get this when right clicking something:
```
Uncaught Error: Received a channel content URI, but claim name and channelName do not match. "name" represents the value in the name position of the URI (lbry://name...), which for channel content will be the channel name. In most cases, to construct a channel URI you should just pass channelName and contentName.
at buildURI (C:\Program Files\LBRY\resources\app.asar\node_modules\lbry-redux\dist\bundle.js:126
```
@dan1d did you run into this during your testing?

Fix convertToShareLink

---

dist/bundle.js
src/redux/reducers/search.js

Setting the search query blank removed the results from the search page. Not setting it blank leaves it there when a user navigates to a search result. This PR fixes both cases: if navigating to the search page, update the query based on the uri, otherwise clear the query.

update search query/activity when navigating

---

src/lbry.js

- Improve media type detection of files with a `contentType` similar to `application/something`         
Most files don't follow  a standar mime-type.
A simple `.pdf` file can contain a vendor-specific mime-type:
```
PDF -> application/x-pdf, application/pdf, application/octet-stream
```
Before:
```JS
const mediaType =
(fileInfo && Lbry.getMediaType(null, fileInfo.file_name)) || Lbry.getMediaType(contentType);
```
After:
```JS
const extname = path.extname(fileName) || mime.getExtension(contenType);
const mediaType = Lbry.getMediaType(contentType, extname);
```
Required by:
https://github.com/lbryio/lbry-app/pull/1576
https://github.com/lbryio/lbry-app/pull/1558

Fix getMediaType logic

---

dist/bundle.js
src/constants/transaction_types.js
src/index.js
src/redux/selectors/wallet.js

replace hard-coded transaction types with constants
to be used by [/lbryio/lbry-desktop/pull/1769](https://github.com/lbryio/lbry-desktop/pull/1769)
the last change at the bottom was from 'send' to 'spend' (now TRANSACTIONS.SPEND) which may have been done on purpose, or exactly the kind of mistake we fix by defining constants

define transaction type constants

---

dist/bundle.js
src/redux/reducers/file_info.js

[/lbryio/lbry-desktop/issues/1612](https://github.com/lbryio/lbry-desktop/issues/1612)
Add `error` property to `fileInfo`. Set true for `uri` when video fails to load. Remove error when video starts to load/play again.

add error handling for file info

---

src/redux/actions/search.js

This prevents the `searchQuery` being updated on every search. We don't want that to happen when we search for recommended content in the app to keep the url bar the actual url and not an empty query.

add isBackgroundSearch param to doSearch function

---

dist/bundle.js
src/index.js
src/redux/actions/search.js
src/redux/reducers/search.js
src/redux/selectors/search.js

- Default first suggestion to be a search
- Most of the search suggestion logic is now in a selector
- Just pass in the api results to the search reducer with a `query` key so previous suggestions are preserved when using the backspace/retyping the same query

Move search suggestion logic to selector

---

dist/bundle.js
src/redux/selectors/claims.js

When getting the recommended content for vanity uris, we can't do a uri match because it won't include a claim id. Just strip out the first result since it should be the same claim.

fix: strip out related content properly on vanity uris

---

dist/bundle.js
src/redux/actions/search.js

Instead of manually replacing the `#` sign, we can just use `encodeURIComponent`
Also fixed an issue where `getState` was undefined

use encodeURIComponent for search query

---

dist/bundle.js
src/index.js
src/redux/selectors/claims.js

In a lot of places we are crafting the channel uri from the claim. It will be a lot simpler if we just add a new selector `makeSelectChannelForClaimUri`

add makeSelectChannelForClaimUri to get channels from uris

---

dist/bundle.js
src/index.js
src/redux/reducers/file_info.js
src/redux/selectors/file_info.js

App crashes when navigating to channel page. FileList now requires sortBy to be passed to it.

Removes unnecessary sort selectors

---

dist/bundle.js
src/redux/reducers/claims.js

This allows us to avoid duplicates when selectingMyClaims, which will pull from `byId` and `pendingById`

delete claim from byId while it's in pending status

---

dist/bundle.js
src/util/formatCredits.js

Before for decimals like `0.00000001` it would format as `0.1e8`

fix creditsToString function for small decimals

---

dist/bundle.js
src/redux/selectors/claims.js

This is a much better solution to ensuring the same piece of content doesn't show up in related when you're at a vanity uri. We build the uri from the claim, then use that to filter against.

search for exact url when filtering related results

---

dist/bundle.js
src/redux/actions/wallet.js

Any place that checks the balance might be checking against a string currently, this makes sure it is always saved as a number.

convert balance to number before saving

---

dist/bundle.js
src/redux/selectors/wallet.js

After some changes to how fees are sent in `transaction_list`, we need to change how we calculate the fee. Before this, updates were showing as 0 fee

fix: correctly show fees on tx's with no balance_delta or value (updates)

---

dist/bundle.js
src/redux/actions/wallet.js

https://github.com/lbryio/lbry/pull/1741/files#diff-96c4bef0747bf57a721011a7dfffa0a6R122
From Tom
> It's a quick call that resets any "reserved" transactions after a send. So it the send fails for some reason, this will help. Otherwise users would need to reset their blockchain.db file.

change: utxo_release before transaction_list

---

dist/bundle.js
src/redux/selectors/search.js

@seanyesmunt This is a minor tweak to the `selectSearchQuery` selector to fallback to `selectSearchValue` since current page and the navigation params are not available for mobile. I'll merge it in, but if you have a better recommendation, please reopen and let me know.

Search tweak

---

package.json

@seanyesmunt I'll merge this since it's a minor change. Since Webpack is no longer used and a `bundle.js` is no longer generated, I updated `main` in `package.json` to refer to `bundle.es.js` so that React Native would make use of that file instead. If this breaks anything else, please let me know. Thanks.

set main to bundle.es.js after removing webpack

---

dist/bundle.es.js
src/util/query_params.js

Quick fix. 
Including `mediaType` in the same search query never returned channels.

fix: remove mediaType when searching for files

---

dist/bundle.es.js
src/redux/actions/claims.js

to use channel uri instead of claim id (support for vanity resolution)
I did not test this locally - would need to bring it into an Android build. The --winning parameter is required so that only the winning channel's claims are returned.

fix:  claim search

---

dist/bundle.es.js
src/index.js
src/lbryURI.js

Regex created to spec at https://spec.lbry.com/#urls
Please note that this allows spaces and other control characters that exist beneath the ascii '!', like bells and linefeeds and whatnot. Not sure if you want this, but the spec BNF reads that way to me...
Test js I used after a `yarn build`:
```
lbryURI = require('./dist/bundle')
console.log(
lbryURI.parseURI('The \u{1F680} Has Landed#917d741cbc652c1ba194dd7efd227f5c93c0bb4b')
);
```

Allow unicode characters in claim names.

---

dist/bundle.es.js
dist/flow-typed/Claim.js
src/redux/actions/claims.js

Controlling means controlling claims, not channels. Added so we only return claims with valid signatures (safer for now, can add options to show invalid later). Also, the claim count in channel is in the signed channel meta object, not the high level one.

fix: controlling and channel claim count meta

---

src/redux/actions/wallet.js

looks like formatCredits was renamed to format-credits.js.
One in actions/wallet was not renamed.
This caused error on `yarn dev` on desktop.
```
ERROR in ../lbry-redux/dist/bundle.es.js
Module not found: Error: Can't resolve 'util/formatCredits' in '/home/jessop/git/vendor/LBRY/lbry-redux/dist'
@ ../lbry-redux/dist/bundle.es.js 17:22-51
@ ./src/platforms/electron/index.js
```

fixes desktop compile error

---

dist/bundle.es.js
src/redux/actions/file.js

This goes along with the commit I made in your lbry-desktop branch. Allows you to download while streaming + re-download already streamed content if it was deleted or settings changed.

fix: streaming + downloads

---

dist/bundle.es.js
flow-typed/mime.js
package.json
src/lbry.js
yarn.lock

It seems to work fine without it, not sure why it was ever added.
I reverted the code back to how it was, but kept the newly added formats

remove mime

---

dist/bundle.es.js
src/index.js
src/lbry.js
src/redux/actions/wallet.js
src/redux/reducers/wallet.js
src/redux/selectors/wallet.js

+ We were not using the total balances stuff I removed -that was an attempt by Akin at one point to work around the SDK cross account balance issue.
+ Decided to keep `balance` as is so we don't have to change it everywhere else...still makes sense I think.

feat: granular balances

---

dist/bundle.es.js
dist/flow-typed/Lbry.js
flow-typed/Lbry.js
src/index.js
src/lbry.js
src/redux/actions/sync.js
src/redux/actions/wallet.js
src/redux/middleware/shared-state.js
src/redux/reducers/blocked.js
src/redux/reducers/tags.js

- now using middleware to handle calling `preference_set`
- changed ACCOUNT_XXX to WALLET_XXX
- There are still more redux changes for the wallet commands but those can be addressed later
- Removed `accountId`, and `walletId` params since they aren't being used anywhere.

changes needed for preference sync

---

dist/bundle.es.js
src/redux/actions/claims.js
src/redux/reducers/claims.js

I think these variable names just got messed up during the changes required for 0.45

handle claimsInChannels for channel fetch so pagination always works

---

dist/bundle.es.js
src/lbryURI.js
src/redux/actions/search.js
src/redux/actions/wallet.js
src/redux/selectors/claims.js
src/redux/selectors/search.js
src/util/query-params.js

https://lbryians.slack.com/archives/C1R07H02X/p1576641588024400?thread_ts=1576637646.019900&cid=C1R07H02X
I think we should just get rid of the search caching, it makes everything so complex. I'd like to do some cleanup when I start working on it more app side, but this should do for now. Passing `related_to={claim_id}` is needed to improve related content a lot.

pass related_to flag to search for recommended content

---

dist/bundle.es.js
src/redux/actions/search.js

This lets me be able to batch resolve the returned URLs instead of waiting for each resolve to return one at a time due to performance reasons.

add optional resolveResults parameter to doSearch

---

dist/bundle.es.js
src/redux/actions/publish.js

There is a deeper issue on edits - will still show you are editing, but at least this would let you publish with the right timestamp.

Fix timestamp if channel has the same name as URL

---

dist/bundle.es.js
src/redux/reducers/claims.js

This was leading to resolved uris going away in inviteNew
I'm interested in any other things that may need to be checked for.
Currently, "Resolve" always overwrites, but fetch channel list doesn't need to.

channel list will no longer overwrite resolved claims byId

---

dist/bundle.es.js
src/redux/actions/claims.js
src/redux/actions/search.js
src/redux/selectors/claims.js

Now that claim_list includes resolve information, we can use canonical_url. This is needed so we can show the repost channel when listing users publishes.

use canonical_url when returning own claim urls and fix lint

---

dist/bundle.es.js
src/redux/actions/comments.js
src/redux/actions/publish.js
src/redux/actions/sync.js
src/redux/selectors/file_info.js
src/redux/selectors/publish.js
src/redux/selectors/search.js
src/util/query-params.js

Sets the `Channel` param as mandatory in `commentCreate`, and provides a toast for the situation.

Enforce channel comments

---

dist/bundle.es.js
src/redux/reducers/publish.js

This addresses navigating away from publish page after having selected a file. Browser security doesn't make it simple to load a file the same as an <input> does without a user-triggered action.

save optimize check state to allow page navigation

---

src/lbry.js

Fixes for: Webp support https://github.com/lbryio/lbry-desktop/issues/4146
> WebP is natively supported in Google Chrome, Firefox, Edge, the Opera browser, and by many other tools and software libraries. Developers have also added support to a variety of image editing tools.
See: https://developers.google.com/speed/webp#webp_support
> Note The comic-book viewer already support this image type.

Enable webp images

---

flow-typed/lbryURI.js
src/lbryURI.js

Current behavior:
If you paste a lbry:// link with a ?t=xyz parameter at the end into the wunderbar, it will start the video at the beginning.
New behavior:
If you paste a lbry:// link with a ?t=xxx parameter at the end into the wunderbar, it will start the video at the xyz seconds timestamp.
This should fix https://github.com/lbryio/lbry-desktop/issues/3972

Support lbry:// links with timestamp

---

src/redux/reducers/publish.js

> Edit previous text or markdown posts directly in the app
Added the contents of the file as string if contentType is "text", this value will be used for the markdown editor
Required by In-app text and markdown publishing and editing [#4105](https://github.com/lbryio/lbry-desktop/issues/4105)

Add file text to publish state

---

dist/bundle.es.js
src/redux/actions/publish.js

Fixes https://github.com/lbryio/lbry-desktop/issues/4385 `Don't show upload progress if no file exists (shows 0% progress)`
An undefined result exception was causing the reflecting-state update code to be missed, so Desktop still thinks the item is still reflecting and continues to show the `Uploading (0%)` status.

Publish: Handle reflecting-state not updated correctly.

---

dist/bundle.es.js
src/redux/reducers/claims.js

So users can abandon claims after directly navigating to the file page

add claim_id to myClaims if resolved claim is mine

---

dist/bundle.es.js
src/redux/reducers/publish.js

Users are annoyed by the constant reset to 'Anonymous'.

Publish: Make 'channel' persistent by not clearing it in CLEAR_PUBLISH

---

dist/bundle.es.js
src/constants/settings.js

Add setting to control the behavior when the app is closed instead of always using the system tray.
See https://github.com/lbryio/lbry-desktop/issues/2220

Add to tray when closed setting

---

README.md
jest.config.js
package.json
tests/config/jest-transformer.js
tests/parseURI.test.js

Suspected there was a bug in parseURI (from strange behaviour seen in lbry-desktop).
Installed and configured jest testing, and added some tests in an attempt to replicate the suspected bug. Discovered that parseURI behaves as expected, but I think it would be good to add the tests anyway.
If this change is accepted, I will probably add more/better testing and include a CI pipeline for this repository.

Add parseURI tests

---

src/redux/actions/wallet.js

Change to variable instead of resolving the variable in the string.

Fix untranslatable string.

---

dist/bundle.es.js
package.json
src/lbryURI.js
src/redux/actions/file.js
yarn.lock

Now that android isn't using this, we can switch back to logging. All `parseURI` uses must be wrapped in a try/catch

throw error instead of logging

---

dist/bundle.es.js
src/redux/reducers/claims.js

https://github.com/lbryio/lbry-desktop/issues/4609
- Don't clear existing results on timeout.
- Mark the "no more results" flag so that the app knows it needs to stop querying.

claim_search: Don't clear previous page results if subsequent pages timeout.

---

dist/bundle.es.js
src/redux/reducers/publish.js

Used by https://github.com/lbryio/lbry-desktop/pull/5578
It properly clears the `uri` property from the publish when clearing the form.
This prevents the following bug:
- Click on edit a claim
- Go back
- Clear form (by calling `doClearPublish`)
- Click on publish
Since the `uri` field isn't cleared, the previous error is shown.

Clear uri when clearing publish

---

dist/bundle.es.js
src/constants/claim.js
src/index.js
src/redux/selectors/claims.js

[5636](https://github.com/lbryio/lbry-desktop/issues/5636): Disable video previews in comments/posts made by channels below a certain channel staked level

Move `getChannelLevel` to a selector.

---

dist/bundle.es.js
src/redux/selectors/claims.js

Closes 5673 (lbry-desktop): `Reposts are all listed under "Annoymous"`

makeSelectClaimForUri: Use either canonical or permanent url for repost data

---

dist/flow-typed/Lbry.js
flow-typed/Lbry.js

Reverts lbryio/lbry-redux#390
Will add this back once the desktop changes are made. It's causing lint to fail.

Revert "connection_status is dead, long live connected"

---

dist/bundle.es.js
src/redux/actions/wallet.js
src/redux/reducers/wallet.js

Closes lbry-desktop [4317: Transaction list shows previously requested data / pages](https://github.com/lbryio/lbry-desktop/issues/4317)
A naive approach of creating a random transaction ID for each fetch. The latest ID, stored in `state`, will be the expected one -- any other transaction results will be dropped.
The loading spinner will continue to spin until the latest ID's results are fetched.
Example of 3 fast filter switches:
This assumes there's no quick, built-in way to abort dispatched tasks (only did a quick Google search for it).  The ability to abort would speed up the wait-time.

Drop old txo-fetch results

---

dist/bundle.es.js
src/index.js
src/redux/selectors/wallet.js
src/util/parse-data.js

Move the file-creation code to the background so that it won't stall the GUI if the list is large.
In actuality, a 100k CSV only took 1 second on my slow VM to generate, so we could avoid this PR if we want.  But I think we should still not do it in the GUI thread in case the columns get larger, or we expand `doFetchTransactions`'s default to beyond 100k entries.

Transaction export: move file-creation to background.

---

dist/bundle.es.js
src/redux/actions/claims.js

I wanted to call claim search from lbry-desktop and dispatch actions (isFetching) before and after success, so that the search, using --include_is_my_output would load results into myClaims.

support claim search async dispatch

---

dist/bundle.es.js
src/redux/actions/wallet.js

https://github.com/lbryio/lbry-desktop/pull/5899 Re-add ability to export transactions
I think this one was missed when merging in 5899.  Oddly, I couldn't find the PR for this item in the Closed section.  Either I forgot to create the PR, or something went wrong because I re-used an old branch name back then.
Anyway, re-created this PR with a new branch.

doFetchTransactions: bump pageSize to 999999; remove doFetchSupport

---

dist/bundle.es.js
src/redux/selectors/publish.js

Publish page tries to set the upload language to the user langauge, and it does so on edit and overwrites the existing value.
https://github.com/lbryio/lbry-desktop/issues/6132
selectPublishFormValues was trying to return "language" from formValues but would always return false, and set the language as default instead, should return "languages" instead.
Also "pendingPublish" was unused

Don't reset content language on edit

---

dist/bundle.es.js
src/index.js
src/redux/selectors/collections.js

[Required for lbryio/lbry-desktop/pull/6393]
https://github.com/lbryio/lbry-desktop/issues/6206 
Added selector to return if a given Claim is in any of a user's collection, needed because other selectors required a list ID

Add claim in collections selector

---

dist/bundle.es.js
dist/flow-typed/npm/from-entries.js
flow-typed/npm/from-entries.js
package.json
src/redux/selectors/collections.js
yarn.lock

#6985 fromentries app crash - fix or add polyfill
Did some guessing, so please verify.
- Added the flow entry, otherwise lint couldn't find the module.  Is this normal?

Fix Object.fromEntries crash on some browsers
